### ISSUE TITLE
roms restart when Bluetooth pad loses connection

### ISSUE THREAD

**Issue by toxicprocyon** [Swordfish90/Lemuroid#56]
In every core, when a bluetooth pad loses connection the rom in execution restarts.

**Comment by Swordfish90** [comment]
Hi, I published 1.4.0 on beta channel, which handles gamepads in a completely different way. Are you still able to reproduce the crash there?

**Comment by toxicprocyon** [comment]
Hello! 1.4.0 installed and the bug persists.

![Screenrecorder-2020-05-07-19-05-26-300_1_1](https://user-images.githubusercontent.com/3154099/81324744-b3d89b00-9097-11ea-9013-9fcf9320c0f6.gif)

**Comment by Swordfish90** [comment]
Hi @toxicprocyon . I made gamepads a bit more robust in latest version (it's already on Google Play Beta as 1.6.0-beta1). Could you please check if the issue is still reproducible?

**Comment by Swordfish90** [comment]
Closed due to inactivity.
