### ISSUE TITLE
libretro core not loaded

### ISSUE THREAD

**Issue by rexendevar** [Swordfish90/Lemuroid#914]
The libretro core was not loaded. This is on a game boy game on android 7.1.1. I strongly suspect that my device simply will not work with the core but I have no idea becuase I don't know how to check.

**Comment by 1BazBiz** [comment]
I had the same thing just after I updated the app. It works on version 1.15, but not on version 1.16

**Comment by furai** [comment]
Probably just need to wait for 1.16.1 in F-Droid.

**Comment by rexendevar** [comment]
lol this was the first time i installed on this device as well. i thought
it was my fault trying to run on old gear. guess i got caught in the
crossfire

**Comment by cmhobbs** [comment]
Same issue for me. 1.15 from f-droid works fine. I'm on the latest grapheneos on a pixel 7 pro. 1.16 from f-droid and the play store both have this issue on my device.

**Comment by SamuXzX** [comment]
Same issure after upgrading to 1.16 from F-Droid: yesterday everything worked, now nohone of the games I play (GBA, NDS, SNES) starts because I get this error about libretro.

**Comment by master1274** [comment]
1.16.0 (no Google Play) has a problem anyway. It doesn’t matter if it’s a github or f-droid build. Everything is fixed in the GitHub 1.16.1 build. It is not clear what exactly is being discussed?

**Comment by SamuXzX** [comment]
Do you mean that it was obvious that we had to wait for 1.16.1 and we didn't need to create an issue?

**Comment by master1274** [comment]
Of course. Because In the current build of Github 1.16.1 the problem has been fixed, then the timeliness of updating in the f-droid is their responsibility. There it was necessary to make a request for an urgent release of the update.The issue was created when the problem was already fixed in the current GitHub build.

**Comment by mimvahedi** [comment]
1.16.1 released on f-droid but still can't load cores on my phone

**Comment by SamuXzX** [comment]
> Of course. Because In the current build of Github 1.16.1 the problem has been fixed, then the timeliness of updating in the f-droid is their responsibility. There it was necessary to make a request for an urgent release of the update.The issue was created when the problem was already fixed in the current GitHub build.

I think the actual problem is that people in this thread didn't know that the next update would have fixed it. Indeed, @furai's comment was enough for me to stop worrying, as I just sit and waited for the new version.
A good behaviour would have been clarifying it for OP and marking this issue as solved.

**Comment by ulville** [comment]
Updated to 1.16.1 from f-droid and the issue persists. 1.15.0 works fine but 1.16.0 and 1.16.1 won't load any libretro cores. My device is Samsung Galaxy S20 FE Snapdragon and runs Android 13

**Comment by master1274** [comment]
> Обновился до 1.16.1 от f-droid, проблема осталась. 1.15.0 работает нормально, но 1.16.0 и 1.16.1 не загружают ядра libretro. Мое устройство — Samsung Galaxy S20 FE Snapdragon и работает под управлением Android 13.

Do a setting reset Lemuroid. This is an update issue from 1.15.0 to 1.16.0/1.16.1

**Comment by ulville** [comment]
I uninstalled and did a fresh install but the issue persisted. Doing a reset from "Lemuroid settings > Advanced settings > Factory reset" fixed the issue 👍🏼

I'm not sure why uninstalling and re-installing didn't fixed the issue though

**Comment by master1274** [comment]
> Я удалил и сделал новую установку, но проблема не исчезла. Выполнение сброса из «Настройки Lemuroid > Расширенные настройки > Сброс к заводским настройкам» устранило проблему 👍🏼
> 
> Я не уверен, почему удаление и повторная установка не решили проблему.

I think that the developer needs to pay attention to this nuance.

**Comment by Algiuxs** [comment]
Close the issue
